version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./devops/server
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - api
      - front
  db:
    container_name: db
    image: db
    build:
      context: ./devops/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=test_db
  api:
    container_name: api
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
  front:
    container_name: front
    image: front
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3001:3000